import Head from 'next/head'
import Image from 'next/image'

export default function bundleDetails() {
 
    return (
        <>
            <Head>
                <title>wp-integrator</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="bundleDetails mt-8 ">
                <div className="search-bar">
                    <span><Image src='/images/search.svg' alt="file not found" width={15} height={15}></Image></span>
                    <input type="text" placeholder="Search Here..."></input>
                </div>

                <section className="bundleDetails-intro mt-8">
                    <div className="container grid">
                        <div className="image">
                            <Image src='/images/wp_integrator/crm_contactform7.svg' alt="file not found" width={492} height={270}></Image>
                        </div>
                        <div className="details">
                            <h1>Contact Form 7 Integration With Zoho CRM</h1>
                            <div className="star flex">
                                <Image src='/images/rating_star.svg' alt="file not found" width={92} height={16}></Image>
                                <div className="content">
                                    <h2>(6 customer reviews)</h2>
                                </div>
                            </div>
                            <div className="content">
                                Send WooCommerce order data easily into Zoho. Order data will be sent to your desired object according to the rules you put in place. Purchase a license below & get complete control over how you use your WooCommerce data.
                            </div>
                            <div className="pricing mt-4">
                                <div className="item flex">
                                    <div className="icon flex mr-2">
                                        <input type="radio" checked></input>
                                    </div>
                                    <div className="text">
                                        Personal - 1 Site ($119.00)
                                    </div>
                                </div>
                                <div className="item flex">
                                    <div className="icon flex mr-2">
                                        <input type="radio" checked></input>
                                    </div>
                                    <div className="text">
                                        Personal - 1 Site ($119.00)
                                    </div>
                                </div>
                                <div className="item flex">
                                    <div className="icon flex mr-2">
                                        <input type="radio" checked></input>
                                    </div>
                                    <div className="text">
                                        Personal - 1 Site ($119.00)
                                    </div>
                                </div>
                            </div>
                            <button className="flex mt-3">
                                <button type="button" className="btn ">Buy Now</button>
                                <button type="button" className="btn btn-outline">View Demo</button>
                            </button>
                        </div>
                    </div>
                </section>

                <section className="desc">

                </section>
            </div>
        </>
    )
}
