import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'



export default function Home() {
  const [checked, setChecked] = useState(false)
  const handleCheck = () => {
    setChecked(prevState=>!prevState)
  }
 


  return (
    <>
      <Head>
        <title>wp-integrator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="wp-integrator mt-6">
        <section className="showcase">
          <div className="container grid grid-fr-1">
            <div className="showcase-text text-center">
              <h1>WordPress Integrations</h1>
              <p>We develop powerful solutions for WooCommerce, the best e-commerce platform for WordPress. We can guarantee 100% compatibility between all our plugins. Check our live demos and launch admin demo for advanced testing.</p>
            </div>
          </div>
        </section>

        <section className="main-content  mt-10">
          <div className="container flex">
            <div className="sidebar br-2">
              <div className="sort-by">
                <h4>SORT BY</h4>
                <div className="sort-by-button mt-2">
                  <button type="button" className="sidebar-btn" id="newest">Newest</button>
                  <button type="button" className="sidebar-btn" id="popular">Popular</button>
                </div>
              </div>
              <div className="filtered-by mt-5">
                <h4>FILTER BY TAG</h4>
                <div className="filter-by-button mt-2 mb-1">
                  <button type="button" className="sidebar-btn">
                    <div className="checkbox" id="forms" onChange={handleCheck}>
                      <span className="mr-1"><input type="checkbox" checked={checked}/></span><span>Forms</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>
                </div>
                {checked ?
                  <div className="filter-sub-button">
                    <button type="button" className="sidebar-btn mb-1">
                      <div className="checkbox">
                        <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                      </div>
                      <div className="count">
                        <span>8</span>
                      </div>
                    </button>

                    <button type="button" className="sidebar-btn mb-1">
                      <div className="checkbox">
                        <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                      </div>
                      <div className="count">
                        <span>8</span>
                      </div>
                    </button>
                    <button type="button" className="sidebar-btn mb-1">
                      <div className="checkbox">
                        <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                      </div>
                      <div className="count">
                        <span>8</span>
                      </div>
                    </button>

                    <button type="button" className="sidebar-btn mb-1">
                      <div className="checkbox">
                        <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                      </div>
                      <div className="count">
                        <span>8</span>
                      </div>
                    </button>

                    <button type="button" className="sidebar-btn mb-1">
                      <div className="checkbox">
                        <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                      </div>
                      <div className="count">
                        <span>8</span>
                      </div>
                    </button>

                    <button type="button" className="sidebar-btn mb-1">
                      <div className="checkbox">
                        <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                      </div>
                      <div className="count">
                        <span>8</span>
                      </div>
                    </button>

                  </div>
                  : ""}

                <div className="filter-by-button mt-2 mb-1">
                  <button type="button" className="sidebar-btn">
                    <div className="checkbox">
                      <span className="mr-1"><input type="checkbox"></input></span><span>WooCommerce</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>
                </div>

                <div className="filter-sub-button">
                  <button type="button" className="sidebar-btn mb-1">
                    <div className="checkbox">
                      <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>

                  <button type="button" className="sidebar-btn mb-1">
                    <div className="checkbox">
                      <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>
                  <button type="button" className="sidebar-btn mb-1">
                    <div className="checkbox">
                      <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>

                  <button type="button" className="sidebar-btn mb-1">
                    <div className="checkbox">
                      <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>

                  <button type="button" className="sidebar-btn mb-1">
                    <div className="checkbox">
                      <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>

                  <button type="button" className="sidebar-btn mb-1">
                    <div className="checkbox">
                      <span className="mr-1"><input type="checkbox"></input></span><span>Newest</span>
                    </div>
                    <div className="count">
                      <span>8</span>
                    </div>
                  </button>

                </div>

              </div>
            </div>


            <div className="integration-list mt-2">
              <div className="search-bar">
                <span><Image src='/images/search.svg' alt="file not found" width={15} height={15}></Image></span>
                <input type="text" placeholder="Search Here..."></input>
              </div>

              <div className="package-list mt-6">
                <div className="card text-center">
                  <div className="feature-img">
                    <Image src='/images/bundle.svg' alt="file not found" width={60} height={60}></Image>
                  </div>
                  <div className="feature-heading">
                    <h3>
                      wpintegrations woocommerce
                      product bundles
                    </h3>
                  </div>
                  <div className="start">
                    <Image src='/images/rating_star.svg' alt="file not found" width={100} height={20}></Image>

                  </div>
                  <div className="feature-desc">
                    <p>
                      Sell gift cards in your shop to increase your earnings and attract new customers.
                    </p>
                  </div>
                </div>
                <div className="card text-center">
                  <div className="feature-img">
                    <Image src='/images/bundle.svg' alt="file not found" width={60} height={60}></Image>

                  </div>
                  <div className="feature-heading">
                    <h3>
                      wpintegrations woocommerce
                      product bundles
                    </h3>
                  </div>
                  <div className="start">
                    <Image src='/images/rating_star.svg' alt="file not found" width={100} height={20}></Image>

                  </div>
                  <div className="feature-desc">
                    <p>
                      Sell gift cards in your shop to increase your earnings and attract new customers.
                    </p>
                  </div>
                </div>

                <div className="card text-center">
                  <div className="feature-img">
                    <Image src='/images/bundle.svg' alt="file not found" width={60} height={60}></Image>

                  </div>
                  <div className="feature-heading">
                    <h3>
                      wpintegrations woocommerce
                      product bundles
                    </h3>
                  </div>
                  <div className="start">
                    <Image src='/images/rating_star.svg' alt="file not found" width={100} height={20}></Image>

                  </div>
                  <div className="feature-desc">
                    <p>
                      Sell gift cards in your shop to increase your earnings and attract new customers.
                    </p>
                  </div>
                </div>

                <div className="card text-center">
                  <div className="feature-img">
                    <Image src='/images/bundle.svg' alt="file not found" width={60} height={60}></Image>

                  </div>
                  <div className="feature-heading">
                    <h3>
                      wpintegrations woocommerce
                      product bundles
                    </h3>
                  </div>
                  <div className="start">
                    <Image src='/images/rating_star.svg' alt="file not found" width={100} height={20}></Image>

                  </div>
                  <div className="feature-desc">
                    <p>
                      Sell gift cards in your shop to increase your earnings and attract new customers.
                    </p>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  )
}
